[Fixes: #25] Remove support for Python 3.5
Sphinx 2.2.0 support has dependencies. Following these dependencies
shows a downstream dependency of snowballstemmer. That dependency is
allowed to any upper limit.

However, a new upgrade of snowballstemmer to 2.0.0 fails.

It fails because it's downstream dependency of yarl requires Python
3.6+:

RuntimeError: yarl 1.4+ requires Python 3.6+

https://travis-ci.org/glenjarvis/badgr-lite/jobs/592955050

Until this is untangled in the dependent libraries, let's remove support
for anything below 3.6. This will, if nothing else, at least communicate
to the consumers what will work.