Update models.py
Delete extensions and entityType from the Badge model's required Json. Now the json from Badgr doesn't include them.

Here we solve te following traceback:

packages\badgr_lite\models.py", line 68, in _check_missing_but_required
    raise exceptions.RequiredAttributesMissingError(
badgr_lite.exceptions.RequiredAttributesMissingError: extensions, entity_type